---
title: "SessionInfo"
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: default
---

Code version: `r system("git log -1 --format=oneline | cut -d' ' -f1", intern = TRUE)`

```{r knitr-opts, include = FALSE}
DOCNAME = "sessionInfo"
knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.path     = paste0("cache/", DOCNAME, "/"),
                      cache.comments = TRUE,
                      echo           = FALSE,
                      error          = FALSE,
                      fig.align      = "center",
                      fig.path       = paste0("figures/", DOCNAME, "/"),
                      fig.width      = 10,
                      fig.height     = 8,
                      dev            = c('svg', 'png'),
                      message        = FALSE,
                      warning        = FALSE)
```

```{r load-libraries, cache FALSE, echo = FALSE}
# RNA-seq
library("scater")
library("splatter")
library("SC3")

# Parallel
library("BiocParallel")

# Plotting
library("cowplot")

# Tables
library("knitr")

# Documents
library("rmarkdown")

# Evaluation
library("clues")

# Data manipulation
library("magrittr")

# devtools
library("devtools")

# Tidyverse
library("tidyverse")
```

```{r load-source, cache = FALSE, echo = FALSE}
source("../R/load_datasets.R")
source("../R/simulate_datasets.R")
source("../R/utils.R")
```

Session information
===================

Details of the R environment and packages used for analysis.

```{r print-session-info, cache = FALSE, echo = FALSE}
info <- session_info()

info.out <- c(paste("Session info", paste0(rep("-", 67), collapse = "")),
             capture.output(info[[1]]),
             "\n",
             paste("Session info", paste0(rep("-", 67), collapse = "")),
             capture.output(info[[2]]))

write_lines(info.out, "../output/sessionInfo.txt")

session_info()
```
